on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Build
        run: dotnet build src -c Release -o build

      - name: Test
        run: |
          dotnet test test -c Release

  generate-documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: mattnotmitt/doxygen-action@v1

      - uses: actions/upload-pages-artifact@v1
        with:
          path: site
      
  deploy:
    if: github.ref_name == 'main'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: generate-documentation
    permissions:
      id-token: write
      pages: write
    runs-on: ubuntu-latest
    steps:
      - id: deployment
        uses: actions/deploy-pages@v1    
