on:
  release:
    types:
      - published

jobs:
  publish:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      
      - name: Build
        run: |
          dotnet pack src -c Release -o build

      - name: Publish
        run: |
          dotnet nuget push build/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} \
          --source https://api.nuget.org/v3/index.json
