on:
  - pull_request
  - push
  - workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        targetPlatform:
          - StandaloneLinux64
          - StandaloneOSX
          - StandaloneWindows64

    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true

      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-

      - uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          buildMethod: CustomBuilderAction.Builder.BuildProject
          buildName: Client
          targetPlatform: ${{ matrix.targetPlatform }}
          unityVersion: 2021.3.23f1

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}
